// Data for programmatic SEO pages.
// Each entry generates one unique page: /templates/x, /industries/x, /use-cases/x

export const TEMPLATES = [
  {
    slug: "bakery",
    name: "Bakery",
    title: "Bakery Website Template",
    meta: "A free bakery website template — menu, story, online ordering and blog built and written for you. Start from the June & Oak template.",
    h1: "Bakery Website Template",
    blurb: "A warm, artisanal site with your menu, your story, online ordering and a journal — designed around your bakery, not a generic template.",
    features: ["Menu section with prices", "Order-ahead cart & checkout", "Story & sourcing pages", "Blog for bakes and specials"],
    accent: "#b3541e",
    grad: "#d9b98c,#b3541e",
  },
  {
    slug: "restaurant",
    name: "Restaurant",
    title: "Restaurant Website Template",
    meta: "Restaurant website with menu, hours, reservations and events. The Metro template — bold, unpretentious, open late.",
    h1: "Restaurant Website Template",
    blurb: "A restaurant site that makes people hungry: full menu, hours, booking and events, written in a voice that sounds like your place.",
    features: ["Full menu with prices", "Reservation & booking form", "Hours & location map", "Events & live music page"],
    accent: "#c0392b",
    grad: "#c98f6e,#7a3c1e",
  },
  {
    slug: "saas",
    name: "SaaS Startup",
    title: "SaaS Website Template",
    meta: "A SaaS landing template with features, pricing, customers and a blog. Start from Northwind — built for product teams.",
    h1: "SaaS Website Template",
    blurb: "A high-converting product site: features, pricing, social proof and a blog — structured for the way software buyers decide.",
    features: ["Feature grid & comparison table", "3-tier pricing with FAQ", "Customer testimonials", "Product blog & newsletter"],
    accent: "#2f6f63",
    grad: "#8aa29e,#3d5a52",
  },
  {
    slug: "portfolio",
    name: "Portfolio",
    title: "Portfolio Website Template",
    meta: "A portfolio template for designers, photographers and creatives. The Atelier template — quiet, confident, precise.",
    h1: "Portfolio Website Template",
    blurb: "Show your work the way it deserves: a gallery, your story, process and contact — without the noise.",
    features: ["Project gallery grid", "Studio / about page", "Process timeline", "Journal & contact"],
    accent: "#6b6355",
    grad: "#c9bda3,#6b6355",
  },
  {
    slug: "wellness",
    name: "Wellness Brand",
    title: "Wellness & Skincare Website Template",
    meta: "A wellness brand template with a shop, farm story and rituals. The Verdant template — grown, not manufactured.",
    h1: "Wellness & Skincare Website Template",
    blurb: "A calm, credible wellness site: product shop with cart, your story, and routines customers trust.",
    features: ["Product shop with cart", "Origin / farm story", "Rituals & journal", "Newsletter signup"],
    accent: "#4d6b45",
    grad: "#a8c3a0,#4d6b45",
  },
  {
    slug: "hotel",
    name: "Hotel",
    title: "Hotel Website Template",
    meta: "A boutique hotel template with rooms, stay details, dining and booking. The Harbor House template.",
    h1: "Hotel Website Template",
    blurb: "Rooms, amenities, dining and direct booking — a hotel site that turns lookers into reservations.",
    features: ["Rooms & rates", "Amenities & stay guide", "Dining page", "Direct booking form"],
    accent: "#24374a",
    grad: "#7f92a8,#24374a",
  },
  {
    slug: "fitness-studio",
    name: "Fitness Studio",
    title: "Fitness Studio Website Template",
    meta: "A fitness studio template with classes, coaches and memberships. Start from a ready-made studio site.",
    h1: "Fitness Studio Website Template",
    blurb: "Class schedules, coach bios, memberships and a free-class CTA — built for a studio that takes training seriously.",
    features: ["Class schedule", "Coach profiles", "Membership tiers", "Free trial booking"],
    accent: "#c0392b",
    grad: "#e08d7a,#a03a2b",
  },
  {
    slug: "clinic",
    name: "Medical Clinic",
    title: "Medical Clinic Website Template",
    meta: "A medical clinic template with services, doctors and appointments. The Willow Health template.",
    h1: "Medical Clinic Website Template",
    blurb: "Services, doctors, transparent pricing and same-week appointments — a clinic site patients trust.",
    features: ["Services list", "Doctor profiles", "Transparent pricing", "Appointment booking"],
    accent: "#2f6f63",
    grad: "#8aa29e,#3d5a52",
  },
  {
    slug: "real-estate",
    name: "Real Estate",
    title: "Real Estate Website Template",
    meta: "A real estate template with listings, agent bios and contact. Built to turn views into tours.",
    h1: "Real Estate Website Template",
    blurb: "Listings, neighborhood guides, agent stories and a booking form — a brokerage site that feels local.",
    features: ["Property listings", "Neighborhood guides", "Agent profiles", "Tour booking"],
    accent: "#8a6d3b",
    grad: "#c9b99a,#8a6d3b",
  },
  {
    slug: "salon",
    name: "Salon & Spa",
    title: "Salon Website Template",
    meta: "A salon and spa template with services, pricing and booking. Beautiful and easy to manage.",
    h1: "Salon & Spa Website Template",
    blurb: "Services, pricing, stylists and online booking — a salon site that fills chairs.",
    features: ["Service menu with prices", "Stylist profiles", "Online booking", "Gallery & reviews"],
    accent: "#9c5a7a",
    grad: "#d9a8c2,#9c5a7a",
  },
  {
    slug: "photography",
    name: "Photography",
    title: "Photography Website Template",
    meta: "A photography portfolio template with galleries, packages and booking. Show your best work.",
    h1: "Photography Website Template",
    blurb: "Galleries, pricing packages and a booking form — a portfolio that sells your eye.",
    features: ["Portfolio galleries", "Pricing packages", "Booking form", "Client proofing"],
    accent: "#37474f",
    grad: "#90a4ae,#37474f",
  },
];

export const INDUSTRIES = [
  {
    slug: "real-estate",
    name: "Real Estate",
    title: "Real Estate Website Builder",
    meta: "Build a real estate website with bukkyai — listings, agent bio and contact. Describe your agency, get the whole site.",
    h1: "Real Estate Website Builder",
    blurb: "Listings, neighborhood pages, agent stories and a booking section — generated from a sentence about your agency.",
    accent: "#8a6d3b",
    grad: "#c9b99a,#8a6d3b",
  },
  {
    slug: "fitness",
    name: "Fitness Studio",
    title: "Fitness Studio Website Builder",
    meta: "A fitness studio website with classes, coaches and memberships. bukkyai writes the whole thing from your brief.",
    h1: "Fitness Studio Website Builder",
    blurb: "Class schedules, coach bios, memberships and a free-class CTA — built and written for your studio.",
    accent: "#c0392b",
    grad: "#e08d7a,#a03a2b",
  },
  {
    slug: "photography",
    name: "Photography",
    title: "Photography Website Builder",
    meta: "A photography portfolio website — galleries, pricing and booking, generated by bukkyai from your brief.",
    h1: "Photography Website Builder",
    blurb: "A portfolio that sells your eye: galleries, packages and a booking form, written in your voice.",
    accent: "#37474f",
    grad: "#90a4ae,#37474f",
  },
  {
    slug: "law-firm",
    name: "Law Firm",
    title: "Law Firm Website Builder",
    meta: "A professional law firm website — practice areas, attorneys and consultations. Built and written by bukkyai.",
    h1: "Law Firm Website Builder",
    blurb: "Practice areas, attorney profiles and a consultation form — trustworthy, clear and confident.",
    accent: "#2b3a55",
    grad: "#8a97ad,#2b3a55",
  },
  {
    slug: "wedding",
    name: "Wedding",
    title: "Wedding Website Builder",
    meta: "A wedding website with details, gallery and RSVP — beautiful, personal and built in minutes.",
    h1: "Wedding Website Builder",
    blurb: "The details, the story, the gallery and the RSVP — everything guests need, beautifully arranged.",
    accent: "#9c5a7a",
    grad: "#d9a8c2,#9c5a7a",
  },
  {
    slug: "consulting",
    name: "Consulting",
    title: "Consulting Website Builder",
    meta: "A consulting website with services, results and booking. Describe your practice, get the whole site.",
    h1: "Consulting Website Builder",
    blurb: "Services, case studies and a booking form — a consulting site that sounds like the person behind it.",
    accent: "#4a5d8a",
    grad: "#9aabcf,#4a5d8a",
  },
  {
    slug: "salon",
    name: "Salon & Spa",
    title: "Salon & Spa Website Builder",
    meta: "Build a salon or spa website — services, pricing, booking and gallery, generated by bukkyai.",
    h1: "Salon & Spa Website Builder",
    blurb: "A salon site that fills chairs: services with prices, stylists, online booking and a gallery.",
    accent: "#9c5a7a",
    grad: "#d9a8c2,#9c5a7a",
  },
  {
    slug: "dental",
    name: "Dental Clinic",
    title: "Dental Clinic Website Builder",
    meta: "A dental clinic website with services, team and appointment booking. Built and written by bukkyai.",
    h1: "Dental Clinic Website Builder",
    blurb: "Treatments, your team, insurance info and easy booking — a clinic site that reassures patients.",
    accent: "#2f6f9f",
    grad: "#9ab8d9,#2f6f9f",
  },
  {
    slug: "plumber",
    name: "Plumber & Home Services",
    title: "Plumber & Home Services Website Builder",
    meta: "A plumber or home-services website with services, service areas and instant contact. bukkyai builds it.",
    h1: "Plumber & Home Services Website Builder",
    blurb: "Services, service areas, reviews and a call button — a site that brings in local jobs.",
    accent: "#2f6f9f",
    grad: "#9ab8d9,#2f6f9f",
  },
  {
    slug: "landscaping",
    name: "Landscaping",
    title: "Landscaping Website Builder",
    meta: "A landscaping website with services, portfolio and quotes. Describe your business, get the site.",
    h1: "Landscaping Website Builder",
    blurb: "Services, a project gallery, service areas and a quote form — built for local growth.",
    accent: "#4d6b45",
    grad: "#a8c3a0,#4d6b45",
  },
  {
    slug: "contractor",
    name: "Contractor",
    title: "Contractor Website Builder",
    meta: "A contractor website with projects, services and estimates. bukkyai writes and designs it.",
    h1: "Contractor Website Builder",
    blurb: "Projects, services, a review section and an estimate form — credibility that wins bids.",
    accent: "#8a6d3b",
    grad: "#c9b99a,#8a6d3b",
  },
  {
    slug: "yoga",
    name: "Yoga & Wellness",
    title: "Yoga Studio Website Builder",
    meta: "A yoga studio website with classes, schedule and booking. Calm, clear and easy to manage.",
    h1: "Yoga Studio Website Builder",
    blurb: "Class schedule, teacher bios, pricing and booking — a calm studio site that fills classes.",
    accent: "#4d6b45",
    grad: "#a8c3a0,#4d6b45",
  },
  {
    slug: "barbershop",
    name: "Barbershop",
    title: "Barbershop Website Builder",
    meta: "A barbershop website with services, barbers and booking. Bold, quick and built for local walk-ins.",
    h1: "Barbershop Website Builder",
    blurb: "Services, barber profiles, gallery and online booking — a barbershop site with an edge.",
    accent: "#37474f",
    grad: "#90a4ae,#37474f",
  },
  {
    slug: "accountant",
    name: "Accountant",
    title: "Accountant Website Builder",
    meta: "An accountant website with services, expertise and contact. Professional, clear and trustworthy.",
    h1: "Accountant Website Builder",
    blurb: "Services, expertise, FAQs and a contact form — an accountant site that builds confidence.",
    accent: "#4a5d8a",
    grad: "#9aabcf,#4a5d8a",
  },
  {
    slug: "coach",
    name: "Life Coach",
    title: "Life Coach Website Builder",
    meta: "A life coach website with services, testimonials and booking. Personal, warm and conversion-ready.",
    h1: "Life Coach Website Builder",
    blurb: "Your approach, testimonials, pricing and booking — a coach site that gets clients to reach out.",
    accent: "#6d5ae8",
    grad: "#a89bff,#6d5ae8",
  },
  {
    slug: "tutoring",
    name: "Tutoring",
    title: "Tutoring Website Builder",
    meta: "A tutoring website with subjects, pricing and booking. Built for tutors and small learning centers.",
    h1: "Tutoring Website Builder",
    blurb: "Subjects, pricing, testimonials and booking — a tutoring site that fills sessions.",
    accent: "#2f6f63",
    grad: "#8aa29e,#3d5a52",
  },
  {
    slug: "nonprofit",
    name: "Non-profit",
    title: "Non-profit Website Builder",
    meta: "A non-profit website with mission, programs and donations. bukkyai builds it free and open.",
    h1: "Non-profit Website Builder",
    blurb: "Mission, programs, impact stats and a donate button — a site that moves people to give.",
    accent: "#2f6f9f",
    grad: "#9ab8d9,#2f6f9f",
  },
  {
    slug: "food-truck",
    name: "Food Truck",
    title: "Food Truck Website Builder",
    meta: "A food truck website with menu, schedule and location. Built and written by bukkyai.",
    h1: "Food Truck Website Builder",
    blurb: "Menu, where you'll be this week, and a way to find you — a food truck site that brings crowds.",
    accent: "#c0392b",
    grad: "#e08d7a,#a03a2b",
  },
  {
    slug: "mechanic",
    name: "Auto Mechanic",
    title: "Auto Shop Website Builder",
    meta: "An auto shop website with services, reviews and booking. Built to bring in local drivers.",
    h1: "Auto Shop Website Builder",
    blurb: "Services, reviews, service areas and a booking form — an auto shop site that earns trust.",
    accent: "#37474f",
    grad: "#90a4ae,#37474f",
  },
];

export const USE_CASES = [
  {
    slug: "small-business",
    name: "Small Business",
    title: "Small Business Website Builder",
    meta: "Build a small business website for free — bukkyai writes your pages, then you edit and publish. No code needed.",
    h1: "Small Business Website Builder",
    blurb: "A real website for your business — services, hours, reviews and contact — generated from one sentence.",
    accent: "#2f6f63",
    grad: "#8aa29e,#3d5a52",
  },
  {
    slug: "online-store",
    name: "Online Store",
    title: "Online Store Website Builder",
    meta: "Create an online store with cart, checkout and coupons — built and written by bukkyai from your product list.",
    h1: "Online Store Website Builder",
    blurb: "Products, cart, coupons and a working checkout — a store that sells, without a platform lock-in.",
    accent: "#8a6d3b",
    grad: "#c9b99a,#8a6d3b",
  },
  {
    slug: "landing-page",
    name: "Landing Page",
    title: "Landing Page Builder",
    meta: "Build a high-converting landing page in minutes. bukkyai writes your copy, headlines and CTA.",
    h1: "Landing Page Builder",
    blurb: "Headline, subcopy, social proof and a clear CTA — a landing page that's written to convert.",
    accent: "#6d5ae8",
    grad: "#a89bff,#6d5ae8",
  },
  {
    slug: "blog",
    name: "Blog",
    title: "Blog Website Builder",
    meta: "Start a blog with bukkyai — posts, categories, RSS and SEO built in. Write or import, publish instantly.",
    h1: "Blog Website Builder",
    blurb: "A blog that's built to be read: posts, categories, RSS feed and SEO from day one.",
    accent: "#4a5d8a",
    grad: "#9aabcf,#4a5d8a",
  },
  {
    slug: "restaurant",
    name: "Restaurant",
    title: "Restaurant Website Builder",
    meta: "Create a restaurant website with menu, hours, reservations and events — written by bukkyai.",
    h1: "Restaurant Website Builder",
    blurb: "A restaurant site that makes people hungry: menu, booking, hours and events.",
    accent: "#c0392b",
    grad: "#c98f6e,#7a3c1e",
  },
  {
    slug: "portfolio",
    name: "Portfolio",
    title: "Portfolio Website Builder",
    meta: "Build a portfolio website that wins clients — gallery, story, process and contact.",
    h1: "Portfolio Website Builder",
    blurb: "Show your best work and get hired: gallery, about, process and contact.",
    accent: "#6b6355",
    grad: "#c9bda3,#6b6355",
  },
  {
    slug: "agency",
    name: "Agency",
    title: "Agency Website Builder",
    meta: "Build an agency website with work, team, process and contact. bukkyai writes it all.",
    h1: "Agency Website Builder",
    blurb: "Selected work, team, process and a pitch-ready contact page — an agency site that wins briefs.",
    accent: "#6d5ae8",
    grad: "#a89bff,#6d5ae8",
  },
  {
    slug: "wedding",
    name: "Wedding",
    title: "Wedding Website Builder",
    meta: "Create a wedding website with details, gallery and RSVP. Beautiful and built in minutes.",
    h1: "Wedding Website Builder",
    blurb: "The details, the story, the gallery and the RSVP — everything guests need.",
    accent: "#9c5a7a",
    grad: "#d9a8c2,#9c5a7a",
  },
  {
    slug: "event",
    name: "Event",
    title: "Event Website Builder",
    meta: "Build an event website with schedule, speakers and tickets. bukkyai writes and designs it.",
    h1: "Event Website Builder",
    blurb: "Schedule, speakers, ticket link and RSVP — an event site that fills seats.",
    accent: "#2f6f9f",
    grad: "#9ab8d9,#2f6f9f",
  },
  {
    slug: "membership",
    name: "Membership",
    title: "Membership Website Builder",
    meta: "Build a membership site with plans and member areas. bukkyai handles the structure and copy.",
    h1: "Membership Website Builder",
    blurb: "Plans, benefits and a clear join CTA — a membership site that converts.",
    accent: "#6d5ae8",
    grad: "#a89bff,#6d5ae8",
  },
  {
    slug: "course",
    name: "Online Course",
    title: "Course Website Builder",
    meta: "Sell an online course with curriculum, pricing and testimonials. Built and written by bukkyai.",
    h1: "Course Website Builder",
    blurb: "Curriculum, pricing, testimonials and enrollment — a course site that sells itself.",
    accent: "#4d6b45",
    grad: "#a8c3a0,#4d6b45",
  },
  {
    slug: "freelancer",
    name: "Freelancer",
    title: "Freelancer Website Builder",
    meta: "Build a freelancer website with services, rates and booking. bukkyai writes your pitch.",
    h1: "Freelancer Website Builder",
    blurb: "Services, rates, testimonials and booking — a freelancer site that books work.",
    accent: "#2f6f63",
    grad: "#8aa29e,#3d5a52",
  },
];

// City × industry local pages (programmatic local SEO).
export const CITIES = ["Austin", "Houston", "Denver", "Phoenix", "Miami", "Seattle", "Portland", "Nashville", "Chicago", "San Diego", "Orlando", "Dallas", "Atlanta", "Boston", "Brooklyn"];
export const LOCAL_INDUSTRIES = [
  ["bakery", "Bakery"],
  ["restaurant", "Restaurant"],
  ["salon", "Salon & Spa"],
  ["plumber", "Plumber"],
  ["fitness-studio", "Fitness Studio"],
  ["landscaping", "Landscaping"],
  ["photography", "Photographer"],
  ["barbershop", "Barbershop"],
];

export const COMPARISONS = [
  {
    slug: "wix",
    name: "Wix",
    title: "bukkyai vs Wix",
    meta: "bukkyai vs Wix: both let you build a website fast. bukkyai writes your copy, exports open HTML and has no lock-in.",
    h1: "bukkyai vs Wix",
    points: [
      ["AI writes your entire site", "Yes — copy, design, pages", "Partial — templates + AI assists"],
      ["Export open HTML you own", "Yes — single file, ZIP, React", "No — locked to the platform"],
      ["No credits or limits", "Yes", "Tiered plans, some limits"],
      ["Custom domain", "Yes (Pro)", "Yes (paid plans)"],
      ["Pricing", "Free to build", "Freemium + paid plans"],
    ],
  },
  {
    slug: "lovable",
    name: "Lovable",
    title: "bukkyai vs Lovable",
    meta: "bukkyai vs Lovable: bukkyai is purpose-built for websites — design, copy and SEO — and exports open HTML.",
    h1: "bukkyai vs Lovable",
    points: [
      ["Purpose", "Websites, marketing & shops", "Apps & products"],
      ["Output", "Static HTML you own", "Full-stack apps"],
      ["Best for", "Businesses & creators", "Developers & founders"],
      ["Learning curve", "Describe → done", "More technical"],
    ],
  },
  {
    slug: "squarespace",
    name: "Squarespace",
    title: "bukkyai vs Squarespace",
    meta: "bukkyai vs Squarespace: get a written, designed site in minutes and export it — or build it template-by-template.",
    h1: "bukkyai vs Squarespace",
    points: [
      ["Time to a full site", "Minutes — AI writes it", "Hours — pick & customize"],
      ["Copywriting", "Included, on-brand", "You write it"],
      ["Export", "Open HTML/React", "Platform-bound"],
    ],
  },
  {
    slug: "wordpress",
    name: "WordPress",
    title: "bukkyai vs WordPress",
    meta: "bukkyai vs WordPress: skip the plugins and hosting — get a finished, fast static site, or export to use WordPress.",
    h1: "bukkyai vs WordPress",
    points: [
      ["Setup", "Describe → site", "Install, theme, plugins"],
      ["Maintenance", "None (static)", "Updates, security"],
      ["Ownership", "Export open files", "You host it"],
      ["Best for", "Speed & simplicity", "Full control & plugins"],
    ],
  },
  {
    slug: "elementor",
    name: "Elementor",
    title: "bukkyai vs Elementor",
    meta: "bukkyai vs Elementor: let AI write and design your site, then edit visually — without dragging widgets.",
    h1: "bukkyai vs Elementor",
    points: [
      ["Building method", "Describe + edit in place", "Drag-and-drop widgets"],
      ["Copywriting", "AI writes it for you", "You write it"],
      ["Output", "Static HTML", "WordPress pages"],
    ],
  },
];

export const HOW_TOS = [
  {
    slug: "make-a-website",
    name: "Make a Website",
    title: "How to Make a Website (2026)",
    meta: "How to make a website in 6 steps — with bukkyai you describe it, approve the plan, edit and publish. No code.",
    h1: "How to Make a Website",
    steps: [
      ["Describe your business", "One or two sentences about what you do and who it's for."],
      ["Approve the plan", "Review the pages and sections before anything is built."],
      ["Let AI write it", "bukkyai writes your copy, design and every page."],
      ["Edit in the preview", "Click any word or image and change it directly."],
      ["Publish or export", "Get a live link, a ZIP, or a React project."],
      ["Own it forever", "Your site is open files — no lock-in."],
    ],
  },
  {
    slug: "make-a-restaurant-website",
    name: "Restaurant Website",
    title: "How to Build a Restaurant Website",
    meta: "Build a restaurant website: menu, hours, reservations and events — written by bukkyai from a one-line brief.",
    h1: "How to Build a Restaurant Website",
    steps: [
      ["Describe the restaurant", "Cuisine, vibe, location — a sentence is enough."],
      ["Approve menu & pages", "Home, menu, hours, reservations, events."],
      ["AI writes the menu copy", "Dishes described appetizingly, prices set."],
      ["Add booking", "A reservation form or Cal.com embed."],
      ["Publish & promote", "Share your link and get tables booked."],
    ],
  },
  {
    slug: "make-a-portfolio",
    name: "Portfolio",
    title: "How to Build a Portfolio Website",
    meta: "Build a portfolio that wins clients — gallery, about, process and contact, written by bukkyai.",
    h1: "How to Build a Portfolio Website",
    steps: [
      ["Describe your work", "What you do and who you want to work with."],
      ["Pick the Atelier template", "A quiet, gallery-led design."],
      ["Add your projects", "Images, captions, categories."],
      ["Write your story", "AI drafts your about and process pages."],
      ["Add contact", "A form that delivers to your inbox."],
    ],
  },
];
